{application,macaba,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{macaba_app,[]}},
              {env,[]},
              {modules,[macaba,macaba_app,macaba_board,macaba_html_handler,
                        macaba_ses,macaba_ses_sup,macaba_sup,macaba_web]}]}.
